### ISSUE TITLE
blank terminals after plots

### ISSUE THREAD

**Issue by hendersonmpa** [ghollisjr/cl-ana#11]
Hello
I have been using cl-ana to create histograms and barcharts. With the last update from quicklisp the resulting terminal(wxt, qt) or file(pdf, png, or svg) is blank.  The behaviour is similar to what happens with a gnuplot session that is expecting more input. 

I am using gnuplot 4.6 patchlevel 4  on ubuntu 14.04 

For example:
``` lisp
(cl-ana.plotting:draw #'sin)
```
creates a blank qt terminal 

Thanks very much.
Matthew

**Comment by ghollisjr** [comment]
I can't reproduce this bug on my system (gnuplot 5.0, Arch Linux), does an older copy of cl-ana still work on your system?

**Comment by hendersonmpa** [comment]
Yes, I reverted to 

```lisp
(ql-dist:install-dist "http://beta.quicklisp.org/dist/quicklisp/2015-10-31/distinfo.txt" :replace t)
```
and it works perfectly again.

I will stick with this dist and experiment with cl-ana from git, try to compile gnuplot 5.0 on Ubuntu 14.01

**Comment by ghollisjr** [comment]
Haven't heard back so I'll close it for now.
