### ISSUE TITLE
Defining quantity methods requires explicit calls to quantity

### ISSUE THREAD

**Issue by djeis97** [ghollisjr/cl-ana#13]
In order to ensure that units are always expanded properly, all quantity methods have to call quantity on their arguments explicitly.

**Comment by djeis97** [comment]
#14 
This is my first solution to the problem- instead of having define-quantity-method define methods for all the applicable data types and pass the problematic arguments through quantity, have it define a default method which just passes all of its arguments through quantity.

**Comment by ghollisjr** [comment]
My latest commit includes your changes except for the default arithmetic method, and I thought we could discuss the pros and cons.

Although having a single default method does result in a simpler macro, it does so at the cost of making quantities the "largest" container so-to-speak, so that every numerical type becomes a quantity if a quantity is encountered during calculations.  My personal preference is for the user to be able to define their own default methods, and it's for this reason that I haven't provided default methods for the cl-ana.generic-math functions.

What do you think?

**Comment by djeis97** [comment]
While leaving the default method open to the user does technically make things more flexible, I have trouble thinking of a situation where the ability to define such a method would be useful. Generally, when I'm using a library, I'm writing more specific methods than the provided ones to add edge case optimization or add support for an extension without stepping on the toes of the rest of the system. In that case, I like already having a sane default available to me which I can override as needed.

On the other hand, the way I was proposing does make the error messages for passing an unsupported datatype a little cryptic- instead of no applicable method, it will complain about not being able to apply quantity to it or it not supporting quantity-scale. 

And then there's optimization issues to consider, at least slightly. Calling quantity everywhere is at least a bit of a cost, and keywords/err-nums are passed through quantity twice the way you have it set up now. Of course, you could just have all the generated methods have the same body instead of having only the quantity methods have the body and have the others recurse.

Finally, I'd like to add another wrinkle to the mix. It's been bothering me for a little while that in some places you use defmethod and in others define-quantity-method. Feels like mixing abstraction layers. Not a serious issue, but I like keeping things like that consistent as much as possible. In my version, it wouldn't be difficult to replace the define-quantity-method macro entirely with something much less intrusive. Say, a macro called with-quantities or as-quantities which takes a list of variables to pass through quantity and and a body of code, and then passes the result through quantity-if-necessary. Then methods could be defined with defmethod and use as-quantities to convert arguments as necessary (which may not be all of them, as in expt). It seems like a more general solution to me, but it makes it more difficult to remove the method duplication that your define-quantity-method does.

I don't know what the best solution is, but those are my thoughts.

**Comment by ghollisjr** [comment]
define-quantity-method is definitely a strange operator to have, and the only reason to have it was to automatically define methods for interacting with non-quantities since there was not a reasonable default available.  This approach is additionally problematic due to needing to call `defquantity` on a type prior to defining any quantity-interacting methods on that type.

Having the default set to treating things as quantities does make sense right now, but clobbering the default method means that if at any future point a situation like we have with quantity comes up again then the user will have to solve their problem in a similar way as define-quantity-method already attempts to do.

It's still not clear to me though, and the optimization issues are definitely worth thinking about.  I'll keep this open for now and see if we can find something that solves all these problems.

**Comment by djeis97** [comment]
Well, I agree- it's a tricky problem without a good solution. One thing I thought of, though, is that (and I know this seems small and nitpicky) perhaps you could add an s onto define-quantity-method (and make it define-quantity-methods). Seems a little dumb, I know, but then code-readability wise it goes from being an odd defmethod syntax to a clear shorthand for a group of related methods.

One possible way to refactor it out would be to have define-quantity-method(s) use the method body both for the main method and for the "q-methods", but also to move the calls to quantity and quantity-if-necessary to another macro as in the with-quantities macro I mentioned above. Then define-quantity-methods just makes sure that the given method body is applied to all the types valid for passing through quantity.

The only issue there that I see off hand is it makes the symbol methods a little awkward, but I don't see any other good way to include them to be honest.

Oh, and a quick implementation of with-quantities to make it exactly clear what I was thinking of:
```
(defmacro with-quantities ((&rest args) &body body)
  (labels ((recursor (args)
             (if args
                 (if (symbolp (car args))
                     `(let ((,(car args) (quantity ,(car args))))
                        ,(recursor (cdr args)))
                     `(with-accessors ((,(caar args) quantity-scale)
                                       (,(cadar args) quantity-unit))
                          (quantity ,(caddar args))
                        ,(recursor (cdr args))))
                 `(progn ,@body))))
    `(quantity-if-necessary
      (block nil
        ;; Block here so that #'return still passes through
        ;; quantity-if-necessary, although #'return-from does
        ;; not (similar to loop)
        ,(recursor args)))))
```

Assuming the above refactor, mult would then be implemented like so:
```
(define-quantity-methods mult (ql qr)
  (with-quantities (ql qr)
    (with-accessors ((scalel quantity-scale)
                     (unitl quantity-unit))
        ql
      (with-accessors ((scaler quantity-scale)
                       (unitr quantity-unit))
          qr
        (make-instance 'quantity
                       :scale (* scalel scaler)
                       :unit (unit-mult unitl unitr))))))
```
Or with the shorthand syntax I added (note: the first version rebinds the variable passed, while the second does not):
```
(define-quantity-methods mult (ql qr)
  (with-quantities ((scalel unitl ql)
                    (scaler unitr qr))
    (make-instance 'quantity
                   :scale (* scalel scaler)
                   :unit (unit-mult unitl unitr))))
```

Feel free to call me an idiot for this, as I suspect that I'm overly biased towards limiting the scope of any given operator and define-quantity-method seems to have set me off somehow. I could very well be going overboard.

**Comment by ghollisjr** [comment]
I've been busy with other things but had some time to think about the problem, and actually I think your version of using the default method makes more sense.  I had forgotten about a huge limitation in define-quantity-methods: All quantity types must be defined before defining any methods, but cl-ana needs to provide arithmetic methods, meaning that the user would need to redefine all methods for their types.  With the default method, all they have to do is define a method on quantity for their type and they get all previously defined quantity methods for free.

Also the with-quantities macro is good Lisp style so I'll use that in defining the default methods.
