### ISSUE TITLE
HDF5 1.10 breaks cl-ana

### ISSUE THREAD

**Issue by ghollisjr** [ghollisjr/cl-ana#18]
Basic file closing operations no longer work with version 1.10, while 1.8 and below still seem to work.

Possibly replace cl-ana's HDF5 code with https://github.com/HDFGroup/hdf5-cffi in the future

**Comment by skilldown** [comment]
@ghollisjr Is this still an issue?

I believe I'm seeing this behavior in hdf5 version 1.12 as well.  `close-hdf-file` returns `-1` with no errors, and the h5 file is never flushed or released.

**Comment by skilldown** [comment]
Merging the pull request #38 and installing hdf5-cffi fixed the issue for me on Linux and Windows.

**Comment by ghollisjr** [comment]
Just merged the PR and added a local copy of hdf5-cffi until upstream can fix the H5I_REFERENCE bug, but now cl-ana works with the current HDF5 standard!
