### ISSUE TITLE
sb-ext:delete-directory can be replaced by uiop:delete-directory-tree

### ISSUE THREAD

**Issue by mirkov** [ghollisjr/cl-ana#20]
I am hoping to use CL-ANA on CCL on Windows.  I replaced several calls of SB-EXT:DELETE-DIRECTORY with UIOP:DELETE-DIRECTORY-TREE

**Comment by ghollisjr** [comment]
Apologies for such a delay.  I'll see about doing ASAP, as there doesn't seem to be any need for an SBCL-specific call.
