### ISSUE TITLE
cl-ana.csv-table: smart-read-from-string should return NIL for empty strings

### ISSUE THREAD

**Issue by kat-co** [ghollisjr/cl-ana#23]
Currently, if an empty string is passed in, an `END-OF-FILE` condition will be raised. Instead, I think this function should return `NIL` for empty strings, to facilitate working with data with nullable fields.

**Comment by ghollisjr** [comment]
Hey thank you for adding this.  I had read the first email notification and added a fix for this before seeing this pull request.  I'll close this issue and if the fix is still lacking something then feel free to add another pull request and I can add it!

**Comment by kat-co** [comment]
Sure thing! I picked this up from other languages, and I'm not sure if it also applies to CL, but:

[`read-from-string`](http://www.lispworks.com/documentation/HyperSpec/Body/f_rd_fro.htm) can optionally take an `eof-error-p` and `eof-value` which will prevent this condition from even arising. This might be faster, and more memory efficient than handling the error.

What do you think?
