### ISSUE TITLE
We would like to name an official chatroom for cl-ana

### ISSUE THREAD

**Issue by kat-co** [ghollisjr/cl-ana#25]
Hey all! I've spoken with @ghollisjr, and we would like to name a place users can go for live help/discussion of cl-ana. I thought I would open an issue to solicit feedback so we can get something going.

Here are the options I'm aware of:

- **#lisp on Freenode**: As far as I can tell, this is where most Common Lisp users chat. A simple "official" pointer here would direct anyone who wants to get help to the room.
- **#cl-ana on Freenode**: IRC is tried and true, and as I mentioned, it's where #lisp is. On the other hand, it's a little anachronistic, and it looks as though it might be getting edged out by newer technologies (e.g. Mozilla is obviating their own IRC network).
- **Matrix**: This is an open protocol which supports federation. There is a free, reference instance in https://matrix.org. The protocol and the client support a lot of the new features expected of newer chat solutions. I personally use this and like it a lot.
- **Discord**: Rust has decided to go with this. It looks like it has all the same benefits as Matrix, but it is proprietary and closed source. There is also an existing [Lisp Discord Server](https://discord.gg/T5D2EAJ). I don't know how popular that is.
- https://gitter.im/: A lot of projects use this because it's tied to your GitHub path. I don't recommend it because it's a closed source, proprietary system. I also don't know how well things can be administered.
- **Slack**: Tons of people use this, and it has a lot of mind-share. I also don't recommend this because it's proprietary, closed source, and you have to pay to keep chat history.

My personal recommendation and preference would be Matrix. I used to be a die-hard IRC user (and I also still idle there using Matrix's IRC bridge), but Matrix is really nice for a couple reasons:
- Users don't have to set up a bouncer just to idle
- Markdown formatting, media, and voice chat are supported out of the box
- Actual clients for every platform: Android, iOS, Gnome, KDE, Windows, Mac, emacs
- Better administration? I don't have a history of administering chatrooms, but the person making this same decision for Mozilla listed difficulties in moderating IRC as one of their pain points. Matrix does have admin levels and what look to be all the usual bells and whistles:
![image](https://user-images.githubusercontent.com/5490961/57172889-f106af00-6deb-11e9-861d-3b9ad2ed8357.png)

EDIT: I forgot about Discord.

**Comment by kat-co** [comment]
It's been 10 days without anyone expressing any preference.

To reiterate, the purpose of a chat room is so that people can get closer to real-time help as they're discovering and learning about the cl-ana. While it is not fair to expect @ghollisjr to be the only one fielding questions, at the moment, my impression is that he has the most knowledge about cl-ana. To this end, because no one has expressed a preference, I'm thinking we should probably see if @ghollisjr is willing to idle in a chatroom, and if so, which technology would be convenient for him.

**Comment by blindglobe** [comment]
I look every so often, but my opinion is that whatever Gary would support,
go with.  The rest can adjust. Unless another developer steps up.

**Comment by ghollisjr** [comment]
I'm trying out Matrix; I've created a room titled "cl-ana":

https://matrix.to/#/!LmTgHWPBTpFUmYybOs:matrix.org?via=matrix.org

**Comment by kat-co** [comment]
Cool, thanks @ghollisjr! It looks like you have permissions on the room set to "invite only". To fix this, from within Riot, you can:

1. Go to room settings
2. "Security and Privacy"
3. "Who can access this room?" -> Anyone who knows the room's link, {including/apart from} guests.

Also, we may need to give it a public address:

1. Room settings
2. General
3. Room Address `#cl-ana:matrix.org`.

Also, should we reflect this somewhere in the README?

**Comment by ghollisjr** [comment]
Ah hopefully it is fixed now; I put a link in the README and will update with the public address: #cl-ana:matrix.org

**Comment by ghollisjr** [comment]
Sorry all; here is a link to a properly configured matrix chatroom:
https://matrix.to/#/!cANztuGawRmRSdyLhu:matrix.org?via=matrix.org
