### ISSUE TITLE
Symbol Clashes

### ISSUE THREAD

**Issue by Davidbhodge** [ghollisjr/cl-ana#3]
Hi,

I am getting a number of clashes when trying to load cl-ana - packages MAP, LIST-UTILS clash with both themselves (eg LIST-transpose) and with alexandria (MEAN, Standard-deviation ) . Is this expected behaviour?

Also, I think some thought needs to be made about package names. I already have a package called gnuplot-interface. Trying to load cl-ana, picks up my gnuplot-interface not yours. Using a prefix (cl-ana?) for internal packages less exposed to environmental issues.

Cheers

**Comment by ghollisjr** [comment]
I'm going to go ahead and close this since it's been about a week with no complaints.
