### ISSUE TITLE
`cl-ana.table:open-plist-table` does not respect lower-case symbols

### ISSUE THREAD

**Issue by kat-co** [ghollisjr/cl-ana#33]
The root cause is because this does not round-trip properly: `(cl-ana.symbol-utils:keywordify (cl-ana.string-utils:lispify :|foo-bar|))`. When `open-plist-table` generates the `field-names`, it calls `lispify` which upper-cases the field name. Later, when calling `table-field-symbols`, the upper-case symbol is produced rather than the case-sensitive symbol.

This causes issues when working with plists with case-sensitive field names since after you create the plist table, if you are `loop`ing over the field symbols and calling `(field-values table field-symbol)`, it won't be able to find the field.

**Comment by ghollisjr** [comment]
Sorry for the delay; lispify call was removed.
