### ISSUE TITLE
Inaccuracies in the "plotting" documentation on the Wiki

### ISSUE THREAD

**Issue by khinsen** [ghollisjr/cl-ana#37]
The Wiki doesn't seem up to date with the code, and since GitHub doesn't support pull requests on Wiki pages, all I can do is point out what's not working.

1. The default terminal type for gnuplot is `qt`, not `wxt` as claimed. If you use a `gnuplot` without `qt` support compiled in, you get neither a plot nor an error message. That took me a lot of time to figure out.

2. The second example, `(draw (plot2d (lines #'sin #'cos)))`, fails because `lines` is `cl-ana.string-utils:lines`, which expects string arguments. I haven't found anything shorter than `(draw (plot2d (list (line #'sin) (line #'cos))))` to get the desired result. The `lines` function is also mentioned under "Plotting structure", but doesn't seem to exist any more.

**Comment by ghollisjr** [comment]
Sorry for those errors in the documentation; it's been updated.

**Comment by khinsen** [comment]
Thanks!
