### ISSUE TITLE
usage: How to read existing hdf5 files

### ISSUE THREAD

**Issue by Davidbhodge** [ghollisjr/cl-ana#4]
Hi Gary,

I have existing netcdf4 files that I am trying to read into CL-ana using hdf5 table. These files are climatology data.

its not clear to me how what I am doing wrong so hopefully you can can comment on this.

As an example here is my code

(defparameter  *hdf5-file* (open-hdf-file  "/Users/dbh/lisp/cl-netcdf/test-data/gis4.nc" :direction :input))

;; returns handle 16777216

(defparameter *temp-table* (open-hdf-table *hdf5* "/tempanomaly"))

; Evaluation aborted on #<SIMPLE-ERROR "Non compound type given to typespec->field-names" {1011EABB73}>.

I can use h5dump to inspect the contents of the file and its  valid. So I am missing some step, just not sure what.

Any advice appreciated

**Comment by ghollisjr** [comment]
Hi David,

In your code here:

(defparameter *temp-table* (open-hdf-table *hdf5* "/tempanomaly"))

you're trying to open a file with variable hdf5, but your file variable is
hdf5-file.  Maybe this is the culprit?

Best,
Gary Hollis

**Comment by Davidbhodge** [comment]
ah - the benefits of not cutting and pasting accurately.
==================
CL-ANA> (defparameter *hdf-file* (open-hdf-file "/Users/dbh/lisp/cl-netcdf/test-data/gis4.nc" :direction :input))
*HDF-FILE*
CL-ANA> *HDF-FILE*
16777217
CL-ANA> (defparameter *hdf-table* (open-hdf-table *hdf-file* "/tempanomaly"))
; Evaluation aborted on #<SIMPLE-ERROR "Non compound type given to typespec->field-names" {10099BDEF3}>.
CL-ANA> 

===========

Same issue. Thoughts?

**Comment by ghollisjr** [comment]
Can I ask what the structure of the data is?  If possible it would even be
nice to have a small sample file which causes this error.

**Comment by Davidbhodge** [comment]
What I'll do is send you an email with a link to the file. Its too large to sen via email.

The original fie is a netcdf classic format which has been converted to netcdf 4 - wheich is HDF compliant.

The HDF tools seems to work happily on it - I can extract data etc etc.

Cheers

**Comment by ghollisjr** [comment]
I uncovered a bug involving table field names which affects HDF5 tables and fixed it; that may explain this problem as well.

There is another issue however involving the formatting of data types in memory which at the moment means that in certain instances a valid HDF5 file will not be handled properly by cl-ana.  This may also be the explanation and unfortunately might take some time before I can fix it.

**Comment by Davidbhodge** [comment]
Hi Gary,
I have been meaning to send you a sample, but just have been real busy over the last couple of weeks
I can send you something tomorrow if you still need it?
Let me know

Sent from Outlook




On Sun, Jun 7, 2015 at 1:25 PM -0700, "Gary Hollis" <notifications@github.com> wrote:












I uncovered a bug involving table field names which affects HDF5 tables and fixed it; that may explain this problem as well.



There is another issue however involving the formatting of data types in memory which at the moment means that in certain instances a valid HDF5 file will not be handled properly by cl-ana.  This may also be the explanation and unfortunately might take some time before I can fix it.

**Comment by ghollisjr** [comment]
That's ok; a sample would be appreciated but there's no rush.

**Comment by Davidbhodge** [comment]
Gary

I have sent you an email to your gmail address with a link to the file

Cheers


> Gary Hollis <mailto:notifications@github.com>
> 9 June 2015 2:35 am
> That's ok; a sample would be appreciated but there's no rush.
>
> On Mon, Jun 8, 2015 at 1:38 AM, Davidbhodge <notifications@github.com>
> wrote:
>
> > Hi Gary,
> > I have been meaning to send you a sample, but just have been real busy
> > over the last couple of weeks
> > I can send you something tomorrow if you still need it?
> > Let me know
> >
> > Sent from Outlook
> >
> >
> >
> >
> > On Sun, Jun 7, 2015 at 1:25 PM -0700, "Gary Hollis" <

**Comment by ghollisjr** [comment]
I've taken a look at the test data file, and this actually exposes the limitations of the HDF5 support in cl-ana.  hdf-table assumes a tabular structure in the dataset, i.e., as used by the H5TB HDF5 library functions,  but the test data is non-tabular.

The functions provided in hdf-cffi should technically allow the data to be analyzed, but at a very low level.  There isn't a nice front end to general HDF5 datasets yet unfortunately.
