### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [ghollisjr/cl-ana#43]
Building with SBCL 2.0.5 / ASDF 3.3.1 for quicklisp dist creation.

Trying to build commit id 2d020565ae99919acb4e361e280a40fecc227ea7

*cl-ana.hdf-typespec* fails to build with the following error:

```
Unhandled PACKAGE-DOES-NOT-EXIST in thread #<SB-THREAD:THREAD "main thread" RUNNING {1000A10083}>: The name "HDF5" does not designate any package.

```

[Full log here](http://report.quicklisp.org/2021-02-27/failure-report/cl-ana.html)

**Comment by ghollisjr** [comment]
Just added missing dependency, that system should build separately now

**Comment by ghollisjr** [comment]
Is it safe to close this?

**Comment by quicklisp** [comment]
Yes, thanks.
