### ISSUE TITLE
System failures - CL-ANA.PATHNAME-UTILS does not exist

### ISSUE THREAD

**Issue by quicklisp** [ghollisjr/cl-ana#7]
http://report.quicklisp.org/2015-09-23/failure-report/cl-ana.html has a log. I'm getting this:

    Unhandled SB-KERNEL:SIMPLE-PACKAGE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {10040956C3}>: The name "CL-ANA.PATHNAME-UTILS" does not designate any package.

That's affecting: 

* cl-ana.table-viewing
* cl-ana.plotting
* cl-ana.makeres
* cl-ana.makeres-table
* cl-ana.makeres-progress
* cl-ana.makeres-macro
* cl-ana.makeres-graphviz
* cl-ana.makeres-branch
* cl-ana.makeres-block

**Comment by ghollisjr** [comment]
Added missing dependency, can you confirm it works?

**Comment by quicklisp** [comment]
Works great now, thanks.
