### ISSUE TITLE
xticslabels option for boxes

### ISSUE THREAD

**Issue by hendersonmpa** [ghollisjr/cl-ana#9]
More of a question than an issue. I would like to create categorical barcharts using the cl-ana gnuplot interface. I have tried a few approaches to get xticlabels to work in the :line-args slots (see below). I wanted to check if I there is a way to do this prior to trying to find my way towards to adding this option.

I would like to replicate this gnuplot code 
```gnuplot
plot 'barplot.dat' using 2:xticlabels(1) with boxes
````
with cl-ana.plotting:draw
```lisp
(cl-ana.plotting:draw  '(("blue" . 3)
                        ("red" . 2)
                        ("green" . 1))
                       :line-args '(:style "boxes"
                                    :line-options "2:xticlabels(1)")
                      :plot-args '(:x-range (0 . 4)
                                   :y-range (0 . 4))
                      :page-args (list :terminal (cl-ana.plotting:wxt-term :size (cons 800 600))))
```

Thanks for a great package

**Comment by ghollisjr** [comment]
Hi hendersonmpa,

Sorry for the delayed response, this is one of the things that still needs to be documented, but the way you would create a categorical barchart would be to use the cl-ana.plotting:tics function to create custom tic labels.  You will need to index your actual data however you wish, and then assign custom tic labels, so for your example:

    (draw '((1 . 3)
            (2 . 2)
            (3 . 1))
          :line-args '(:style "boxes")
          :plot-args (list :x-range '(0 . 4)
                           :y-range '(0 . 4)
                           :x-tics (tics :manual-labels
                                         (list (list :name "blue"
                                                     :position 1)
                                               (list :name "red"
                                                     :position 2)
                                               (list :name "green"
                                                     :position 3)))))
